name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🏗️ Dependencies'
    labels:
      - 'dependencies'
  - title: '⚡ Performance'
    labels:
      - 'performance'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Installation

  ```bash
  # Using pnpm (recommended)
  pnpm add solid-styles@$RESOLVED_VERSION

  # Using npm
  npm install solid-styles@$RESOLVED_VERSION

  # Using yarn  
  yarn add solid-styles@$RESOLVED_VERSION

  # Using bun
  bun add solid-styles@$RESOLVED_VERSION
  ```

  ## Package Stats
  - 🎯 **100% Test Coverage**
  - ⚡ **Zero Runtime CSS-in-JS**
  - 🌊 **Spring Physics Animations**
  - 📱 **SSR Ready**

  ## What's New
  
  This release includes improvements to the solid-styles library for SolidJS applications. See the changes above for detailed information.

  ---

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
